### PR TITLE
Merge compiler changes

### PR DESCRIPTION
**Pull request by liam923**
Bring Merlin up to date with Flambda commit [47edce8a3ec5b9ea699628aa1d88697254cfc8a4](https://github.com/ocaml-flambda/flambda-backend/commit/47edce8a3ec5b9ea699628aa1d88697254cfc8a4)

### CODE REVIEW

**Comment by goldfirere** [comment]
How should we review this? It doesn't look like the conflicts were checked in. So my instinct is to skip the first two commits and review the rest. Does that sound right, @liam923?

**Comment by liam923** [comment]
> How should we review this? It doesn't look like the conflicts were checked in. So my instinct is to skip the first two commits and review the rest. Does that sound right, @liam923?

@goldfirere Yes. There were no actual conflicts, which is why there's no commit resolving conflicts. The first to commits were simply the result of the import script. Everything after that is manual resolution of other errors (type errors, failing tests, and handling new flags).

**Comment by goldfirere** [comment]
Great. Reviewing now.

**Review by goldfirere — APPROVED** [review]
All but commit a636d8fc3454163f240b046abace7dc5e9c4515c

**Review by ccasin — APPROVED** [review]
zero_alloc changes look fine.

As a minor request: In the future a more specific PR title would be helpful, just to make things easier when searching the history.  Almost every PR here merges compiler changes, so mentioning for what release or for what feature is useful.

**Pull request merged**
